// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TheGameOfGovernment {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GoG_Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoG_Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TheGameOfGovernment.GoG_Resources", typeof(GoG_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string GOODS_COUNT {
            get {
                return ResourceManager.GetString("GOODS_COUNT", resourceCulture);
            }
        }
        
        internal static string GOOD_WITH_NUM {
            get {
                return ResourceManager.GetString("GOOD_WITH_NUM", resourceCulture);
            }
        }
        
        internal static string GOOD_NAME {
            get {
                return ResourceManager.GetString("GOOD_NAME", resourceCulture);
            }
        }
        
        internal static string GOOD_IMPORTANCE {
            get {
                return ResourceManager.GetString("GOOD_IMPORTANCE", resourceCulture);
            }
        }
        
        internal static string GOOD_PRICE {
            get {
                return ResourceManager.GetString("GOOD_PRICE", resourceCulture);
            }
        }
        
        internal static string BUDGET_INITIAL {
            get {
                return ResourceManager.GetString("BUDGET_INITIAL", resourceCulture);
            }
        }
    }
}
